In [24]:
import numpy as np

# Example usage:
a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)
c = np.random.rand(3, 4)
d = np.random.rand(3, 1)
e = np.random.rand(5, 3)
f = np.random.rand(5)
g = np.random.rand(4, 3, 2)
h = np.random.rand(5, 5)
i = np.array([0, 1])
j = np.array([1, 2])
l = np.random.rand(4, 5)
n = np.random.rand(4, 6)
o = np.array([[1, 2, 3], [4, 5, 6]])
p = np.array([[1, 2, 3], [4, 1, 6], [7, 8, 9]])



In [25]:
def elementwise_multiplication(a, b):
    return a * b
print(elementwise_multiplication(a, b))

[[[0.59744708 0.84880739 0.0526732  0.20004631]
  [0.01100306 0.61292195 0.52838655 0.19451824]
  [0.3585485  0.01040412 0.13687173 0.07992529]]

 [[0.49806815 0.61152297 0.36011449 0.32137421]
  [0.14273311 0.05366817 0.47198376 0.01845005]
  [0.46943165 0.07645103 0.1209385  0.08878163]]]


In [26]:
def broadcast_operations(c, d):
    try:
        addition = c + d
        subtraction = c - d
        multiplication = c * d
        division = c / d
    except ValueError:
        print("Broadcasting not possible for given shapes.")
        return None, None, None, None
    return addition, subtraction, multiplication, division
print(broadcast_operations(c, d))

(array([[1.40987635, 1.70159678, 1.48755209, 0.97614295],
       [1.40936182, 1.76095498, 1.30490335, 1.76138156],
       [1.10740789, 0.97504618, 1.62114498, 0.77997458]]), array([[-0.35950009, -0.06777966, -0.28182435, -0.79323349],
       [-0.17134682,  0.18024633, -0.27580529,  0.18067291],
       [-0.22983409, -0.36219579,  0.28390301, -0.55726739]]), array([[0.46462775, 0.72270938, 0.53334656, 0.08090892],
       [0.48923525, 0.76711842, 0.40667605, 0.76745557],
       [0.29338213, 0.20488232, 0.63687753, 0.07445335]]), array([[0.59364205, 0.92338582, 0.68144218, 0.10337509],
       [0.78320252, 1.22805763, 0.65103589, 1.22859736],
       [0.65625655, 0.45829431, 1.42460978, 0.16654218]]))


In [27]:
def outer_product(e, f):
    return e[:, :, np.newaxis] * f[np.newaxis, np.newaxis, :]
print(outer_product(e, f))

[[[0.08125532 0.03835902 0.10822607 0.06858036 0.12663758]
  [0.10939366 0.05164256 0.14570424 0.09232941 0.17049158]
  [0.579403   0.27352459 0.77172186 0.48902231 0.90300786]]

 [[0.32016559 0.15114379 0.42643684 0.27022317 0.49898265]
  [0.15386889 0.07263843 0.20494196 0.12986699 0.23980687]
  [0.12901121 0.06090362 0.17183337 0.10888683 0.20106581]]

 [[0.43525231 0.20547393 0.57972382 0.36735759 0.67834695]
  [0.24135123 0.1139371  0.32146195 0.20370301 0.37614934]
  [0.25318382 0.11952303 0.33722209 0.21368985 0.39459061]]

 [[0.15814626 0.0746577  0.21063911 0.13347713 0.24647321]
  [0.30322143 0.14314479 0.40386848 0.25592212 0.47257494]
  [0.17723735 0.08367021 0.23606701 0.14959021 0.27622694]]

 [[0.37064581 0.17497449 0.49367275 0.31282901 0.57765679]
  [0.5719878  0.27002403 0.76184537 0.4827638  0.89145117]
  [0.36114149 0.17048769 0.48101371 0.30480727 0.56284418]]]


In [28]:
def extract_elements(g):
    return g[::2, ::2, :]
print(extract_elements(g))

[[[0.98624995 0.52532151]
  [0.12389646 0.24324905]]

 [[0.592878   0.73032234]
  [0.46471205 0.00883013]]]


In [29]:
def sum_diagonal_elements(h, i, j):
    k = np.array([h[i[m], j[n]] for m in range(len(i)) for n in range(len(j))])
    return k.reshape(len(i), len(j))
print(sum_diagonal_elements(h, i, j))

[[0.88472506 0.66433503]
 [0.68649551 0.37044757]]


In [30]:
def reshape_and_flatten(n):
    reshaped = n.reshape(2, 2, 6)
    flattened = reshaped.reshape(4, 6)
    return flattened
print(reshape_and_flatten(n))

[[0.93511913 0.39993078 0.94521833 0.24563404 0.07394927 0.96645688]
 [0.29465364 0.85856291 0.48989016 0.78053001 0.98830899 0.36432602]
 [0.22011757 0.93091794 0.58197038 0.69475358 0.49443989 0.37573598]
 [0.25472169 0.56414784 0.59840126 0.43141756 0.18741926 0.43782066]]


In [31]:
def row_col_mean_product(l):
    row_means = l.mean(axis=1, keepdims=True)
    col_means = l.mean(axis=0, keepdims=True)
    return row_means * col_means
print(row_col_mean_product(l))

[[0.31764197 0.28102952 0.33019305 0.14672713 0.31865046]
 [0.22091629 0.19545276 0.22964542 0.10204701 0.22161768]
 [0.49057657 0.43403112 0.50996088 0.22661014 0.49213412]
 [0.29057143 0.25707922 0.30205287 0.13422254 0.29149397]]


In [32]:
def roll_array(o, positions):
    return np.roll(o, positions, axis=0)
print(roll_array(o, 1))

[[4 5 6]
 [1 2 3]]


In [33]:
def replace_with_mean(p, x):
    rows, cols = p.shape
    mean_replacement = p.copy()
    for i in range(rows):
        for j in range(cols):
            if p[i, j] == x:
                neighbors = []
                if i > 0:
                    neighbors.append(p[i - 1, j])
                if i < rows - 1:
                    neighbors.append(p[i + 1, j])
                if j > 0:
                    neighbors.append(p[i, j - 1])
                if j < cols - 1:
                    neighbors.append(p[i, j + 1])
                if neighbors:
                    mean_replacement[i, j] = np.mean(neighbors)
    return mean_replacement
print(replace_with_mean(p, 1))

[[3 2 3]
 [4 5 6]
 [7 8 9]]
